CREATE TABLE restaurantes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    nombre VARCHAR2(150 CHAR) NOT NULL UNIQUE,

    telefono NUMBER(15,0) UNIQUE,

    correo VARCHAR2(100 CHAR) UNIQUE,

    -- ====== DIRECCION (EMBEDDED) ======
    calle VARCHAR2(50 CHAR),
    numero NUMBER(14,0),
    colonia VARCHAR2(50 CHAR),
    ciudad VARCHAR2(40 CHAR),
    estado VARCHAR2(40 CHAR),
    codigo_postal NUMBER(10,0),

    -- ====== AUDITORIA ======
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--Menus--
CREATE TABLE menus (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    nombre VARCHAR2(100 CHAR)
        DEFAULT 'Menu sin nombre'
        NOT NULL,

    descripcion CLOB,

    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    restaurante_id NUMBER,

    CONSTRAINT fk_menus_restaurante
        FOREIGN KEY (restaurante_id)
        REFERENCES restaurantes(id)
        ON DELETE CASCADE
);
